sudo: required

dist: trusty

language: rust

os:
  - windows

rust:
  - stable

before_script:
  - choco install llvm

script:
  - (cd croaring-sys && cargo test)
  - cargo test
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo bench
